name: build_on_tag.yaml
on:
  release:
    types: [published]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Set up Poetry
        run:
          python -m pip install poetry
      - name: Install dependencies
        run:
          poetry install
      - name: Build package
        run:
          poetry build
      - name: Output release tag
        id: get_release_tag
        run: echo "RELEASE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Add wheel to release assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dist/${{ env.RELEASE_TAG }}-py3-none-any.whl
          asset_name: ${{ env.RELEASE_TAG }}-py3-none-any.whl
          asset_content_type: application/octet-stream